# Generated by Django 4.2.6 on 2023-11-30 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)])),
                ('semester', models.CharField(choices=[('Fa', 'Fall'), ('Su', 'Summer'), ('Sp', 'Spring'), ('Wi', 'Winterim')], default=('Fa', 'Fall'), max_length=8)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(2000)])),
                ('credits', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)])),
                ('section_type', models.CharField(choices=[('Lec', 'LECTURE'), ('Lab', 'LAB'), ('Dis', 'DISCUSSION')], max_length=3)),
                ('section_is_on_monday', models.BooleanField(default=False)),
                ('section_is_on_tuesday', models.BooleanField(default=False)),
                ('section_is_on_wednesday', models.BooleanField(default=False)),
                ('section_is_on_thursday', models.BooleanField(default=False)),
                ('section_is_on_friday', models.BooleanField(default=False)),
                ('section_start_time', models.TimeField(default='00:00')),
                ('section_end_time', models.TimeField(default='00:00')),
                ('location', models.CharField(max_length=20)),
                ('course_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.section')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='N/A', max_length=20)),
                ('address', models.CharField(default='N/A', max_length=20)),
                ('type', models.CharField(choices=[('SU', 'Supervisor'), ('IN', 'Instructor'), ('TA', 'Teaching Assistant')], default=('TA', 'Teaching Assistant'), max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
