# Generated by Django 4.2.6 on 2023-11-18 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_num', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('Fa', 'FALL'), ('Su', 'SUMMER'), ('Sp', 'SPRING'), ('Wi', 'WINTERIM')], max_length=2)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.IntegerField(default=0)),
                ('section_type', models.CharField(choices=[('Lec', 'LECTURE'), ('Lab', 'LAB'), ('Dis', 'DISCUSSION')], max_length=3)),
                ('section_is_on_monday', models.BooleanField(default=False)),
                ('section_is_on_tuesday', models.BooleanField(default=False)),
                ('section_is_on_wednesday', models.BooleanField(default=False)),
                ('section_is_on_thursday', models.BooleanField(default=False)),
                ('section_is_on_friday', models.BooleanField(default=False)),
                ('section_start_time', models.TimeField(default='00:00')),
                ('section_end_time', models.TimeField(default='00:00')),
                ('location', models.CharField(max_length=20)),
                ('course_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.section')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
