# Generated by Django 4.2.6 on 2023-11-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_num', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_num', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('course_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
            ],
        ),
    ]
