# Generated by Django 4.2.7 on 2023-12-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
    ]
