# Generated by Django 4.2.6 on 2023-11-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassignments',
            old_name='user',
            new_name='user_id',
        ),
    ]
