# Generated by Django 4.2.6 on 2023-11-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
