# Generated by Django 4.2.6 on 2023-11-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0002_rename_user_userassignments_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassignments',
            name='course_num',
        ),
        migrations.AddField(
            model_name='section',
            name='section_end',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_start',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
