# Generated by Django 4.2.6 on 2023-11-19 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TAScheduler', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='N/A', max_length=20)),
                ('address', models.CharField(default='N/A', max_length=20)),
                ('type', models.CharField(choices=[('SUP', 'Supervisor'), ('INS', 'Instructor'), ('TA', 'Teaching Assistant')], default=('TA', 'Teaching Assistant'), max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
