# Generated by Django 4.2.6 on 2023-11-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0003_remove_userassignments_course_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_end',
            new_name='section_end_time',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_start',
            new_name='section_start_time',
        ),
    ]
