# Generated by Django 4.2.6 on 2023-11-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0004_rename_section_end_section_section_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_is_on_friday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_is_on_monday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_is_on_thursday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_is_on_tuesday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_is_on_wednesday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
