# Generated by Django 4.2.6 on 2023-11-16 19:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TAScheduler', '0005_section_section_is_on_friday_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAssignments',
            new_name='UserAssignment',
        ),
    ]
